@Library('GissFwDevOps@3.10.2') _

FwAutoAgent(
	[ 
	"XLDEPLOY_ENABLE":"false",
	"HELM_DEPLOY":"true",
	"UNIT_TEST":"true",
	"CD": "true",
	"COMPILABLES":"java",
	"KIUWAN_APP":"MAC0",
	"TYPE_REGRESION":"SELENIUM_MAVEN"
    ]
)